services:
  hub: 
    image: selenium/hub:4.25.0
  chrome:
    image: selenium/node-chromium:4.25.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 2
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: selenium/node-firefox:4.25.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 2
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  amine-raptor:
    image: raptor22sq/seleniumnew
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=vendor-portal-main.xml
    volumes:
      - /c/Users/User/OneDrive/Documents/Workspace/05-dockerize/grid-test-suites/output/vendor-portal:/home/selenium-docker/test-output

  amine-raptor-flight:
    image: raptor22sq/seleniumnew
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=flight-reservation-main.xml
    volumes:
      - /c/Users/User/OneDrive/Documents/Workspace/05-dockerize/grid-test-suites/output/flight:/home/selenium-docker/test-output












    #command: ["sh", "-c", "ping nginx"]  # Automatically ping nginx service


##deploy: replicas: 4: This mapping sets four replicas for the Chrome container.
##Scaling locally: Instead of defining replicas in the docker-compose.yaml file, you can run docker-compose up --scale chrome=4 if you're not using Docker Swarm. This command tells docker-compose to create four Chrome containers in your local environment.


##to scale containers you need to remove containers name chrome and firefox