services:
  amine-raptor:
    image: raptor22sq/seleniumautomation
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=vendor-portal-main.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
      #- /c/Users/User/OneDrive/Documents/Workspace/05-dockerize/grid-test-suites/output/vendor-portal:/home/selenium-docker/test-output

  amine-raptor-flight:
    image: raptor22sq/seleniumautomation
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=flight-reservation-main.xml
    volumes:
      - ./output/flight:/home/selenium-docker/test-output
      #- /c/Users/User/OneDrive/Documents/Workspace/05-dockerize/grid-test-suites/output/flight:/home/selenium-docker/test-output
